# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install sqlmodel pyjwt fastapi polars httpx requests
          pip install passlib python-multipart python-dotenv

      - name: Set environment variables for tests
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> $GITHUB_ENV
          echo "ES_USERNAME=${{ secrets.ES_USERNAME }}" >> $GITHUB_ENV
          echo "ES_PASSWORD=${{ secrets.ES_PASSWORD }}" >> $GITHUB_ENV

      - name: Run tests and coverage
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest --cov=backend --cov-fail-under=50 backend/test/
