# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install sqlmodel pyjwt fastapi polars httpx requests passlib python-multipart

      - name: Run tests and coverage
        run: |
          cd backend
          pytest --cov=. --cov-fail-under=88 test/
